#!/bin/bash
export DEBIAN_FRONTEND=noninteractive;
sudo -i;
sudo apt-get -y update;
sudo apt-get -y install mysql-server mysql-client mysql-workbench libmysqld-dev;
sudo apt-get -y install apache2 php5 libapache2-mod-php5 php5-mcrypt phpmyadmin;
sudo /usr/bin/mysqladmin -u root -h localhost password "test123";
sudo /etc/init.d/mysql restart;
sudo apt-get install php5-curl;
sudo bash -c 'echo "Include /etc/phpmyadmin/apache.conf" >> /etc/apache2/apache2.conf';
sudo chmod 777 -R /var/www/;
sudo printf "<?php\nphpinfo();\n?>" > /var/www/html/info.php;
sudo service apache2 restart;
sudo php5enmod mcrypt;
sudo service apache2 restart;
sudo a2enmod rewrite;
sudo service apache2 restart;
sudo apt-get -y install zip;
#mysqladmin -u root password "";
